INSERT INTO tblCards (hp, name, type_id, stage_id, info, attack, damage, weak, resistance, retreat, cardNumberInCollection, collection_id) VALUES 
(70, 'Wartortle', 3, 2, 'Often hides in water to stalk unwary prey.', 'Withdraw', '0', 'Lightning', NULL, '1', 42, 1),
(100, 'Blastoise', 3, 3, 'A brutal Pokémon with pressurized water jets on its shell.', 'Hydro Pump', '40+', 'Lightning', NULL, '3', 2, 1),
(50, 'Bulbasaur', 1, 1, 'A strange seed was planted on its back at birth.', 'Leech Seed', '20', 'Fire', NULL, '1', 44, 1),
(80, 'Ivysaur', 1, 2, 'When the bulb on its back grows large, it loses the ability to stand on its hind legs.', 'Vine Whip', '30', 'Fire', NULL, '1', 30, 1),
(310, 'Mewtwo ex', 5, 6, 'It was created by a scientist after years of horrific gene-splicing.', 'Psycho Drive', '220', 'Psychic', NULL, '2', 151, 2),
(100, 'Dragonite', 9, 3, 'It is said that this Pokémon lives somewhere in the sea.', 'Hyper Beam', '60', 'None', NULL, '3', 4, 1),
(60, 'Charmander', 2, 1, 'The flame at the tip of its tail makes a sound as it burns.', 'Ember', '30', 'Water', NULL, '1', 46, 1),
(80, 'Charmeleon', 2, 2, 'When it swings its burning tail, it elevates the temperature to unseen levels.', 'Flamethrower', '50', 'Water', NULL, '1', 24, 1),
(30, 'Magikarp', 3, 1, 'In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.', 'Flail', '10x', 'Lightning', NULL, '1', 129, 2),
(230, 'Gyarados ex', 3, 6, 'It has a stray, violent nature. It is capable of destroying entire cities.', 'Tyrannical Tail', '180', 'Lightning', NULL, '4', 225, 2),
(60, 'Abra', 5, 1, 'Using its ability to read minds, it will identify impending danger and teleport to safety.', 'Psyshock', '10', 'Psychic', NULL, '0', 63, 2),
(80, 'Kadabra', 5, 2, 'It emits special alpha waves from its body that induce headaches.', 'Super Psych', '50', 'Psychic', NULL, '1', 64, 2),
(160, 'Alakazam ex', 5, 6, 'It is said to have an IQ of approximately 5,000.', 'Dimensional Hand', '120', 'Psychic', NULL, '1', 65, 2),
(60, 'Gastly', 5, 1, 'Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep.', 'Sleeping Gas', '0', 'Darkness', 'Fighting', '0', 92, 2),
(80, 'Haunter', 5, 2, 'Because of its ability to slip through block walls, it is said to be from another dimension.', 'Nightmare', '30', 'Darkness', 'Fighting', '1', 93, 2),
(130, 'Gengar', 5, 3, 'Under a full moon, this Pokémon likes to mimic the shadows of people.', 'Poltergeist', '50x', 'Darkness', 'Fighting', '1', 94, 2),
(340, 'Teralord Rayquaza', 11, 7, 'Rules the ozone layer with a shimmer of cosmic energy.', 'Astral Burst', '300', 'None', NULL, '2', 280, 3),
(280, 'Lucario VSTAR', 6, 5, 'It has the ability to sense the auras of all things.', 'Aura Star', '70x', 'Psychic', NULL, '2', 79, 3),
(60, 'Eevee', 10, 1, 'An extremely rare Pokémon that may evolve in a number of different ways.', 'Tail Whap', '10', 'Fighting', NULL, '1', 133, 2),
(200, 'Sylveon ex', 5, 6, 'It sends a soothing aura from its ribbonlike feelers to calm fights.', 'Magical Shot', '160', 'Metal', NULL, '1', 180, 3);