INSERT INTO tblCards (hp, name, type_id, stage_id, info, attack, damage, weak, resistance, retreat, cardNumberInCollection, collection_id) VALUES 
(50, 'Squirtle', 3, 1, 'After birth, its back swells and hardens into a shell.', 'Bubble', '10', 'Lightning', NULL, '1', 63, 1),
(70, 'Machoke', 6, 2, 'Its muscular body is so powerful, it must wear a lead belt.', 'Submission', '60', 'Psychic', NULL, '3', 34, 1),
(100, 'Machamp', 6, 3, 'Using its four arms, it can execute many punches simultaneously.', 'Seismic Toss', '60', 'Psychic', NULL, '3', 8, 1),
(40, 'Vulpix', 2, 1, 'At the time of its birth, it has only one snowy-white tail.', 'Confuse Ray', '10', 'Water', NULL, '1', 37, 2),
(120, 'Ninetales', 2, 2, 'Very smart and very vindictive.', 'Fire Blast', '120', 'Water', NULL, '1', 38, 2),
(50, 'Diglett', 6, 1, 'Lives about one yard underground where it feeds on plant roots.', 'Mud Slap', '30', 'Grass', 'Lightning', '0', 50, 2),
(90, 'Dugtrio', 6, 2, 'A team of Diglett triplets. It triggers huge earthquakes.', 'Slash', '40', 'Grass', 'Lightning', '0', 51, 2),
(60, 'Psyduck', 3, 1, 'While lulled to sleep by its headache, it uses strange powers.', 'Water Gun', '20', 'Lightning', NULL, '1', 54, 2),
(110, 'Golduck', 3, 2, 'Its slim and lymphatic body allows it to swim fast.', 'Hyper Beam', '70', 'Lightning', NULL, '1', 55, 2),
(60, 'Growlithe', 2, 1, 'Very protective of its territory.', 'Flare', '20', 'Water', NULL, '1', 58, 2),
(130, 'Arcanine', 2, 2, 'A Pokémon that has been admired since the past for its beauty.', 'Take Down', '80', 'Water', NULL, '3', 59, 2),
(60, 'Poliwag', 3, 1, 'Its slick black skin is thin, but also very flexible.', 'Water Bomb', '30', 'Lightning', NULL, '1', 60, 2),
(90, 'Poliwhirl', 3, 2, 'It can live in or out of water.', 'Double Slap', '30x', 'Lightning', NULL, '1', 61, 2),
(140, 'Poliwrath', 3, 3, 'An adept swimmer at both the front crawl and breaststroke.', 'Submission', '90', 'Lightning', NULL, '3', 62, 2),
(70, 'Tentacool', 3, 1, 'It drifts in sea currents. Use its poisonous tentacles to sting.', 'Acid', '10', 'Lightning', NULL, '1', 72, 2),
(120, 'Tentacruel', 3, 2, 'It has 80 tentacles that stretch and contract freely.', 'Toxic Whip', '80', 'Lightning', NULL, '2', 73, 2),
(60, 'Ponyta', 2, 1, 'Its hooves are 10 times harder than diamonds.', 'Smash Kick', '20', 'Water', NULL, '1', 77, 2),
(100, 'Rapidash', 2, 2, 'Very competitive, this Pokémon will chase anything that moves fast.', 'Agility', '40', 'Water', NULL, '0', 78, 2),
(220, 'Snorlax ex', 10, 6, 'It is not satisfied unless it eats over 880 pounds of food every day.', 'Heavy Impact', '140', 'Fighting', NULL, '4', 143, 2),
(210, 'Articuno ex', 3, 6, 'A legendary bird Pokémon that is said to appear to doomed people.', 'Ice Wing', '110', 'Lightning', 'Fighting', '1', 144, 2),
(210, 'Zapdos ex', 4, 6, 'A legendary bird Pokémon that is said to appear from clouds while wielding lightning.', 'Thunder Blast', '120', 'Lightning', 'Fighting', '1', 145, 2),
(210, 'Moltres ex', 2, 6, 'One of the legendary bird Pokémon. It is said that its appearance indicates the coming of spring.', 'Flare Float', '110', 'Water', 'Fighting', '1', 146, 2),
(300, 'Dragonite ex', 9, 6, 'It can fly around the globe in about 16 hours.', 'Dragon Pulse', '200', 'None', NULL, '2', 149, 2),
(320, 'Mega Tyranitar ex', 7, 7, 'Its body can’t be harmed by any sort of attack.', 'Mountain Crush', '280', 'Fighting', NULL, '4', 210, 3),
(270, 'Mega Gardevoir ex', 5, 7, 'It will give its life to protect its trainer.', 'Brilliant Blast', '240', 'Metal', NULL, '2', 195, 3),
(310, 'Mega Lucario ex', 6, 7, 'It readies itself by sensing the auras of its enemies.', 'Aura Strike', '260', 'Psychic', NULL, '1', 202, 3),
(190, 'Entei V', 2, 1, 'It is said that when it roars, a volcano erupts somewhere.', 'Burning Roar', '100+', 'Water', NULL, '2', 44, 3),
(190, 'Raikou V', 4, 1, 'The rain clouds it carries allow it to fire thunderbolts at will.', 'Lightning Dash', '120', 'Fighting', NULL, '1', 45, 3),
(190, 'Suicune V', 3, 1, 'Said to be the reincarnation of north winds.', 'Blizzard Bind', '100', 'Lightning', NULL, '2', 46, 3),
(340, 'Arceus VSTAR', 10, 5, 'It is said to have emerged from an egg in a place where there was nothing.', 'Star Birth', '200', 'Fighting', NULL, '2', 125, 3);