INSERT INTO tblCards (hp, name, type_id, stage_id, info, attack, damage, weak, resistance, retreat, cardNumberInCollection, collection_id) VALUES 
(100, 'Kangaskhan', 10, 1, 'The female raises its young in a pouch on its belly.', 'Comet Punch', '20x', 'Fighting', 'Psychic', '3', 5, 1),
(120, 'Lapras', 3, 1, 'A gentle soul that can read the minds of people.', 'Water Gun', '10+', 'Lightning', NULL, '2', 10, 1),
(70, 'Pinsir', 1, 1, 'If it fails to crush the victim with its pincers, it will swing them around.', 'Guillotine', '50', 'Fire', NULL, '1', 9, 1),
(50, 'Ditto', 10, 1, 'It can freely recombine its own cellular structure to transform.', 'Morph', '0', 'Fighting', 'Psychic', '1', 3, 1),
(30, 'Caterpie', 1, 1, 'Its short feet are tipped with suction pads.', 'String Shot', '10', 'Fire', NULL, '1', 45, 1),
(40, 'Metapod', 1, 2, 'This Pokémon is vulnerable to attack while its shell is soft.', 'Stiffen', '0', 'Fire', NULL, '2', 54, 1),
(70, 'Butterfree', 1, 3, 'In battle, it flaps its wings at high speed to release toxic dust.', 'Whirlwind', '40', 'Fire', 'Fighting', '0', 33, 1),
(40, 'Weedle', 1, 1, 'Often found in forests, eating leaves.', 'Poison Sting', '10', 'Fire', NULL, '1', 49, 1),
(60, 'Kakuna', 1, 2, 'Almost incapable of moving, this Pokémon can only harden its shell.', 'Poison Powder', '20', 'Fire', NULL, '2', 33, 2),
(100, 'Beedrill', 1, 3, 'Flies at high speed and attacks using its large venomous stingers.', 'Twineedle', '30x', 'Fire', NULL, '0', 15, 2),
(40, 'Pidgey', 10, 1, 'A common sight in forests and woods.', 'Gust', '10', 'Lightning', 'Fighting', '1', 57, 1),
(60, 'Pidgeotto', 10, 2, 'Very protective of its sprawling territorial area.', 'Mirror Move', '0', 'Lightning', 'Fighting', '1', 22, 1),
(100, 'Pidgeot', 10, 3, 'This Pokémon flies at Mach 2 speed, seeking prey.', 'Hurricane', '60', 'Lightning', 'Fighting', '0', 8, 1),
(30, 'Rattata', 10, 1, 'Bites anything when it attacks.', 'Quick Attack', '10+', 'Fighting', 'Psychic', '0', 61, 1),
(60, 'Raticate', 10, 2, 'It uses its whiskers to maintain its balance.', 'Super Fang', '?', 'Fighting', 'Psychic', '1', 40, 1),
(40, 'Spearow', 10, 1, 'Eats bugs in grassy areas.', 'Mirror Move', '0', 'Lightning', 'Fighting', '1', 62, 1),
(90, 'Fearow', 10, 2, 'With its huge and magnificent wings, it can keep aloft without ever having to land.', 'Agility', '20', 'Lightning', 'Fighting', '0', 36, 1),
(60, 'Ekans', 7, 1, 'Moves silently and stealthily.', 'Bite', '20', 'Psychic', NULL, '1', 56, 2),
(90, 'Arbok', 7, 2, 'It is rumored that the ferocious warning markings on its belly differ from area to area.', 'Terror Strike', '60', 'Psychic', NULL, '2', 24, 2),
(50, 'Sandshrew', 6, 1, 'Burrows deep underground in arid locations.', 'Sand-Attack', '10', 'Grass', 'Lightning', '1', 62, 2),
(100, 'Sandslash', 6, 2, 'Curls up into a spiny ball when threatened.', 'Slash', '70', 'Grass', 'Lightning', '1', 27, 2),
(320, 'Stellar Terapagos ex', 11, 6, 'A Pokémon that holds the power of every type within its shell.', 'Star Reign', '240', 'Fighting', NULL, '2', 170, 3),
(250, 'Lugia VSTAR', 10, 5, 'It is said to be the guardian of the seas.', 'Tempest Dive', '220', 'Lightning', 'Fighting', '2', 139, 3),
(280, 'Giratina VSTAR', 9, 5, 'It was banished for its violence. It silently gazed upon the old world.', 'Lost Impact', '280', 'None', NULL, '2', 131, 3),
(330, 'Mega Mewtwo Y ex', 5, 7, 'Its mental powers are focused to a sharp point.', 'Psychic Infinity', '10+', 'Psychic', NULL, '2', 200, 3),
(340, 'Mega Gengar ex', 5, 7, 'It can take the powers of those it haunts.', 'Hollow Geist', '200', 'Darkness', 'Fighting', '1', 205, 3),
(310, 'Mega Blastoise ex', 3, 7, 'The cannons on its back are as powerful as tank guns.', 'Hydro Bombard', '250', 'Lightning', NULL, '3', 212, 3),
(300, 'Mega Venusaur ex', 1, 7, 'The flower on its back blooms with incredible vitality.', 'Crisis Vine', '210', 'Fire', NULL, '4', 215, 3),
(330, 'Koraidon ex', 6, 6, 'A legendary Pokémon that traveled through time.', 'Kaiser Drive', '280', 'Psychic', NULL, '2', 230, 3),
(330, 'Miraidon ex', 4, 6, 'It is said to be a Paradox Pokémon from the future.', 'Photon Blaster', '280', 'Fighting', NULL, '2', 231, 3);